### ISSUE TITLE
course_list 課程留言數有誤

### ISSUE THREAD

**Issue by tinglo** [ShareClass/ShareClass#103]

**Comment by JIElite** [comment]
@tinglo 

目前採取了一種方式修改。
但是由於已經存在在 DB 的 comment 在數量上無法同步，所以顯示可能還是會有錯誤
除非把之前的 comment 砍掉。

我還在思考是不是要採用其他改法，但是比較複雜

**Comment by JIElite** [comment]
目前已修正
