### ISSUE TITLE
編輯個人名稱 中間有空格，按下確認會不見

### ISSUE THREAD

**Issue by JIElite** [ShareClass/ShareClass#131]
編輯時：
<img width="304" alt="2017-05-27 8 31 03" src="https://cloud.githubusercontent.com/assets/6872274/26521462/81a63dda-431b-11e7-9591-4a25ef63e4d0.png">

按下確認後:
<img width="305" alt="2017-05-27 8 31 09" src="https://cloud.githubusercontent.com/assets/6872274/26521465/89cfb072-431b-11e7-8131-3d444fe84b26.png">

空格會不見！暫時標記為 bug，但是不算緊急的。

@tinglo

**Comment by tinglo** [comment]
要允許名字中間有空格嗎

**Comment by JIElite** [comment]
@tinglo 中間可以有

**Comment by tinglo** [comment]
ok, done

**Comment by JIElite** [comment]
@tinglo reviewed

**Comment by JIElite** [comment]
solved wit #198
