### ISSUE TITLE
前後端都要檢查課程上傳時，欄位的長度

### ISSUE THREAD

**Issue by JIElite** [ShareClass/ShareClass#132]
課程標題目前沒有檢查長度，會導致上傳的時候發生錯誤

並且錯誤發生後，按掉 error message 之後，不能重新直接上傳
針對這個問題，先行修復欄位長度檢查的部分。

<img width="637" alt="2017-05-27 8 44 32" src="https://cloud.githubusercontent.com/assets/6872274/26521583/83095e70-431e-11e7-99ab-36aebb7b48b9.png">

<img width="629" alt="2017-05-27 8 49 13" src="https://cloud.githubusercontent.com/assets/6872274/26521584/84a5ca16-431e-11e7-8c49-12258dc715b3.png">

@tinglo

**Comment by JIElite** [comment]
backend done

**Comment by tinglo** [comment]
frontend done

**Comment by cheng-kuan** [comment]
教材名稱 ＆ 英文數字排版

**Comment by tinglo** [comment]
ok , done

**Comment by cheng-kuan** [comment]
test ok
