### ISSUE TITLE
課程評論列表得 show more 能不能讓觸及範圍變大？

### ISSUE THREAD

**Issue by JIElite** [ShareClass/ShareClass#139]
![2017-05-29 1 17 41](https://cloud.githubusercontent.com/assets/6872274/26530712/bf8b2bc8-440c-11e7-9617-450890116e5a.png)

show more 可以點選的範圍太小，不太方便。建議做成一個長條圓弧狀的 bar 可以點選。
字體也可以調整一下

**Comment by tinglo** [comment]
目前改成一個button
