### ISSUE TITLE
分享課程時，按下上傳課程後，把上傳課程的按鈕 lock 住。

### ISSUE THREAD

**Issue by JIElite** [ShareClass/ShareClass#143]
因為在網路不好的使用者上，如果上傳的速度不夠快，一開始他們會以為他們沒有按下按鈕
尤其是一些觸控板比較不好的筆電上更是如此，會以為我自己沒有按下按鈕

在重複按下 上傳課程 的按鈕後，反而會導致無法上傳 error 的情況，這樣使用者要重新上傳更麻煩。
我自己在使用 macbook 的時候，有時候都會懷疑有沒有按下按鈕。

<img width="700" alt="2017-05-29 3 35 39" src="https://cloud.githubusercontent.com/assets/6872274/26540747/69f2785a-4485-11e7-8502-72e73310767f.png">

雖然是標記為 enhancement 可是我覺得這還滿重要的！

@tinglo

**Comment by tinglo** [comment]
ok, done
