### ISSUE TITLE
帳戶註冊欄位驗證問題

### ISSUE THREAD

**Issue by JIElite** [ShareClass/ShareClass#144]
1. username 的部分，目前是 email, 預設最大長度為: 255
2. 密碼的部分，即使輸入只有 3 位，依然可以讓使用者送出。希望可以擋一下不讓使用者送出註冊

<img width="535" alt="2017-05-31 12 08 50" src="https://cloud.githubusercontent.com/assets/6872274/26593191/d00bb4a6-4595-11e7-8a01-955df0fa706a.png">

**Comment by JIElite** [comment]
@tinglo  如果覺得不需要改的話也沒關係。
只是提出來討論一下，我後端也有 Validation

**Comment by tinglo** [comment]
目前我先檔密碼格式不符的部份，因為註冊部份是很久以前寫的code
validation的方式寫的有點爛，想等下禮拜三忙完之後改一下這邊的code

**Comment by JIElite** [comment]
後端這邊做好 Validation 了
@tinglo 你幫我 check 一下就好了，覺得沒有問題就 tag 我, close issue

**Comment by tinglo** [comment]
check ok, 我有改code, 晚點pr
