### ISSUE TITLE
發送重置密碼信件時，不需要立即的 alert

### ISSUE THREAD

**Issue by JIElite** [ShareClass/ShareClass#146]
我們使用 email 重置密碼的時候，不需要直接 Response 已傳送信件的訊息
可以直接讓使用者等 1 分鐘後在收信。

或是如果要直接 Response 寄送信件的訊息的話，可能要做轉圈圈的動畫，讓人家知道有在處理。

@tinglo

**Comment by JIElite** [comment]
然後希望按下按鈕後，也把按鈕 lock 住，以免二次傳送。

**Comment by tinglo** [comment]
ok, done
