### ISSUE TITLE
下載教材名稱更名

### ISSUE THREAD

**Issue by JIElite** [ShareClass/ShareClass#152]
@tinglo  這個能不能修一下？
目前教材的名稱 prefix 滿固定的 就是 uuid_, 應該可以修修看

**Comment by tinglo** [comment]
html download tag可以設定filename , 但好像要same-origin 才有作用, 我可能要再survey 一下

**Comment by JIElite** [comment]
@tinglo  ok.

**Comment by tinglo** [comment]
@JIElite 
伯駿大大幫我試出了方法
除了前端要 https://ausdemmaschinenraum.wordpress.com/2012/12/06/how-to-save-a-file-from-a-url-with-javascript/
s3也要做這樣的調整 http://docs.aws.amazon.com/AmazonS3/latest/user-guide/add-cors-configuration.html

**Comment by tinglo** [comment]
想要問一下，有點忘記教材前面為什麼要編碼

**Comment by tinglo** [comment]
ok, fixed
