### ISSUE TITLE
上傳課程流程確認

### ISSUE THREAD

**Issue by JIElite** [ShareClass/ShareClass#165]
我預想的流程是這樣:

1. 上傳教材之前先利用 presigned 的功能，得到可以上傳的 destination url (bucket, key 已決定好)
2. 同步資料庫的教材物件，同步完確定教材物件都在 Database 的時候，創建課程才不會有教材不存在的情況。因為創建課程的時候，會去檢查要夾帶在該課程的教材是否都成功創建
3. 創建課程到 Database

必須依照上述步驟操作，要是順序性的缺一不可。
但是先前在創建課程的時候，有些課程仍會出現 TeachingMaterial Doesn't exist 的錯誤訊息
如: https://shareclass.xyz/course/4d796ef709d24c05bfaf8f5d231f6072/
這是搜尋 "學思達" 的第一個課程，至今仍未知道是什麼錯誤。

所以想要來檢查一下是不是 Javascript 同步與非同步的問題
再麻煩 @tinglo  檢查一下步驟是不是正確？謝謝

**Comment by tinglo** [comment]
@JIElite 
我這邊確認js的步驟是：
先上傳filename到presigned->取得url->將檔案上傳到s3上->sync上傳的課程
->確認sync完後上傳課程所有資訊(課程名稱、課程介紹、msterial....)到後端

應該是跟你說的步驟是一樣的，會不會是之前有bug導致那個課程的錯誤，但現在已經修復了？

**Comment by JIElite** [comment]
@tinglo 目前已經修復了，應該是後端問題
