### ISSUE TITLE
社群的課程清單沒有顯示時間

### ISSUE THREAD

**Issue by JIElite** [ShareClass/ShareClass#169]
Please take a look:
https://shareclass.xyz/community/2/%E6%95%B8%E5%AD%B8%E6%95%99%E5%AD%B8%E7%A4%BE%E7%BE%A4/course/

@tinglo 
@cheng-kuan 
有空可以幫忙看一下，是什麼問題？然後回覆 issue，謝謝

**Comment by tinglo** [comment]
已修復
