### ISSUE TITLE
編輯課程，去掉所有教材時，無法操作

### ISSUE THREAD

**Issue by JIElite** [ShareClass/ShareClass#170]
<img width="722" alt="2017-06-10 2 42 38 1" src="https://user-images.githubusercontent.com/6872274/26989746-caa7effe-4d86-11e7-992f-31027c2eba34.png">
<img width="715" alt="2017-06-10 2 42 46" src="https://user-images.githubusercontent.com/6872274/26989747-cab85cae-4d86-11e7-9e62-0d3528a305e7.png">
<img width="709" alt="2017-06-10 2 42 54" src="https://user-images.githubusercontent.com/6872274/26989748-cac33ba6-4d86-11e7-9dce-9835157e865b.png">

@tinglo  XDDDD

**Comment by tinglo** [comment]
???
我有設定會跳通知說不能上傳

**Comment by tinglo** [comment]
喔我懂了

**Comment by JIElite** [comment]
@tinglo  reviewed

**Comment by JIElite** [comment]
solved with #198
