### ISSUE TITLE
個人資訊頁面，課程列表太多造成頁面顯示錯誤

### ISSUE THREAD

**Issue by JIElite** [ShareClass/ShareClass#174]
<img width="1258" alt="2017-06-12 3 46 41" src="https://user-images.githubusercontent.com/6872274/27014010-e5ad4a82-4f21-11e7-8457-a9d55a3563ed.png">
<img width="1266" alt="2017-06-12 3 46 48" src="https://user-images.githubusercontent.com/6872274/27014011-e5b081e8-4f21-11e7-8677-cc7f518f10f2.png">

@tinglo XDDDDDDDDDDDDDD

**Comment by tinglo** [comment]
~'~
你是創了幾個啊？我之前自己這邊側沒問題噎

**Comment by JIElite** [comment]
@tinglo 如果我做分頁 對你來說會不會比較方便處理這個問題？因為我準備弄成分頁了

**Comment by tinglo** [comment]
done, 我這個只要調一下css就好了

**Comment by cheng-kuan** [comment]
test ok.
