### ISSUE TITLE
封面圖會因為 Browser Size 而沒有填滿

### ISSUE THREAD

**Issue by JIElite** [ShareClass/ShareClass#24]
在瀏覽器條小的時候，像是 < 100% 的時候，就會出現這個問題

<img width="1221" alt="2017-04-06 2 03 21" src="https://cloud.githubusercontent.com/assets/6872274/24719688/3dd364ec-1a6d-11e7-8b4b-d72e9345a1df.png">

**Comment by tinglo** [comment]
@JIElite

**Comment by JIElite** [comment]
@tinglo  ok, check fixed.
