### ISSUE TITLE
登入的時候，重登要多加空白的問題

### ISSUE THREAD

**Issue by JIElite** [ShareClass/ShareClass#27]
在登出，重新登入後，回到登入頁面發現登入按鈕不能直接按
需要修改欄位資料後，才能夠按下登入。

@tinglo

**Comment by tinglo** [comment]
@JIElite

**Comment by JIElite** [comment]
@tinglo 這個也是修在這個 branch 嗎？fix/issue-frontend

**Comment by tinglo** [comment]
嗯嗯對
