### ISSUE TITLE
上傳課程流程錯誤，略過完整課程類別

### ISSUE THREAD

**Issue by JIElite** [ShareClass/ShareClass#65]
在填寫類別填寫到一半的時候，先去填寫課程簡介，就可以略過選擇完全部的類別
<img width="608" alt="2017-04-06 1 36 22" src="https://cloud.githubusercontent.com/assets/6872274/24718719/9b417172-1a69-11e7-8ab9-de99412a6e20.png">

略過填寫完整的課程類別後，嘗試上傳會卡在進度條跑滿的畫面
<img width="624" alt="2017-04-06 1 38 23" src="https://cloud.githubusercontent.com/assets/6872274/24718779/d8a29eec-1a69-11e7-89bd-5372ca2c8215.png">

使用檢查來查看 console 會得到這樣的結果：
<img width="1147" alt="2017-04-06 1 39 29" src="https://cloud.githubusercontent.com/assets/6872274/24718800/f2d25104-1a69-11e7-98a6-292de407e1bd.png">

**Comment by tinglo** [comment]
@JIElite

**Comment by JIElite** [comment]
@tinglo  這個是修在哪一個 branch 呀？

**Comment by tinglo** [comment]
應該是修改在 feauture/modifiy-issue-frontend, 現在merge後develop也OK了

**Comment by JIElite** [comment]
@tinglo  Ok. close
