### ISSUE TITLE
上傳課程時，課程簡介的框框可以拉出來超出限制範圍

### ISSUE THREAD

**Issue by JIElite** [ShareClass/ShareClass#66]
<img width="916" alt="2017-04-06 1 58 06" src="https://cloud.githubusercontent.com/assets/6872274/24719517/a2b04a66-1a6c-11e7-85d8-98f2911e313e.png">

教材簡介的部分也是
<img width="873" alt="2017-04-06 1 59 49" src="https://cloud.githubusercontent.com/assets/6872274/24719570/c96402e2-1a6c-11e7-92fb-91e983417ddb.png">

**Comment by tinglo** [comment]
@JIElite

**Comment by JIElite** [comment]
@tinglo ok. check fixed
