### ISSUE TITLE
尋找課程時，在特定範圍內無法點擊

### ISSUE THREAD

**Issue by JIElite** [ShareClass/ShareClass#70]
當我們把滑鼠移到項目清單的這個位置的時候，游標會變成可以點選的手指
<img width="1221" alt="2017-04-08 1 51 56" src="https://cloud.githubusercontent.com/assets/6872274/24812920/9ca7fcca-1bfe-11e7-94e3-13162d86de27.png">

可是雖然游標變換了，但是點擊下去卻沒有任何反應。在 Chrome 左下角的狀態列也沒有顯示 URL
估計在以下範圍內都有這個問題：
<img width="1148" alt="2017-04-08 1 57 52" src="https://cloud.githubusercontent.com/assets/6872274/24813014/fefe591e-1bfe-11e7-9f4a-a2a372d1efc9.png">

**Comment by tinglo** [comment]
@JIElite

**Comment by JIElite** [comment]
@tinglo ok, check fixed.
