### ISSUE TITLE
上傳課程時，例外教材檔案的處理

### ISSUE THREAD

**Issue by JIElite** [ShareClass/ShareClass#77]
目前允許傳輸的檔案是 doc, docx, pdf

在上傳課程的頁面，並沒有看到能夠上傳哪些檔案類型的提示
此外，如果上傳錯誤的檔案類型，並沒有相對應的處理

@tinglo

**Comment by tinglo** [comment]
@JIElite 
目前用文字提醒

**Comment by JIElite** [comment]
@tinglo  ok, check fixed
