### ISSUE TITLE
User Profile 課程清單 URL 錯誤

### ISSUE THREAD

**Issue by JIElite** [ShareClass/ShareClass#80]
目前在 feature/community 的 branch 上，有額外修改 course url serialize 加上 /。
而造成在 User Profile 點選課程時，有連結錯誤的狀況。

待確認加上 / 與不加上 / 哪一種做法比較好之後，再另行決定

@tinglo

**Comment by tinglo** [comment]
目前前端部份都先改成不加 /

**Comment by JIElite** [comment]
ok
